// Generated by CoffeeScript 1.3.1
(function() {
  document.writeln('<script type="text/javascript" src="common/js/stats.js"></script>');
  document.writeln('<script type="text/javascript" src="common/js/jquery.js"></script>');
  document.writeln('<script type="text/javascript" src="common/js/jquery.easing.1.3.js"></script>');
  document.writeln('<script type="text/javascript" src="common/js/jquery.common.js"></script>');
  document.writeln('<script type="text/javascript" src="common/js/jquery.mousewheel.min.js"></script>');
  document.writeln('<script type="text/javascript" src="common/js/imageLoader.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/canvas.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/bgCanvas.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/bgImage.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/base.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sequence.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/start.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/concept.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/technology.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/skincare.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/interview.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/history.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/sections/end.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/controller.js"></script>');
  document.writeln('<script type="text/javascript" src="assets/js/main.js"></script>');
}).call(this);